name: deploy-test
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed] #他のjobがある想定でこの設定にしている

jobs:
  UploadStaticFiles:
    name: Upload static files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      = run: npm ci
      - run: yarn build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: static-files
        run: aws s3 sync . s3://rest-test-env --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"

  